import { Link } from "react-router-dom";
import Slika from "./Slike/slika3.jpg";
import Slika2 from "./Slike/slika4.jpg";
import Slika3 from "./Slike/slika5.jpg";
function Povijest() {
    return (
      <div className="Povijest">
        <table>
            <th>
                <Link to="/" className='linkovi'><td>Početna</td></Link>
                <Link to="/o" className='linkovi'><td>O</td></Link>
            </th>
        </table>
        <h1>Povijest Formule 1</h1><hr></hr>
        <div className="slikaDesno"><img src={Slika}></img><br></br>Alfa Romeo 159 iz 1951.</div>
        <p>Prva utrka Svjetskog prvenstva Formule 1 se održala 13. svibnja 1950. godine na stazi Silverstone u Velikoj Britaniji. Na toj utrci je pobijedio Giuseppe Farina u svojoj Alfetti 158 ispred druge dvije Alfe. Prvo prvenstvo je osvojio Talijan Giuseppe Farina u Alfi 1950., za dlaku pobijedivši svog argentinskog momčadskog vozača Juana Manuela Fangia. Ipak je Fangio osvojio naslov 1951. i još četiri sljedeća u narednih 6 godina dok mu nije dvostruki svjetski prvak Alberto Ascari poremetio planove vozeći za Ferrari. Iako se Britanac Stirling Moss redovito natjecao nikad nije uspio osvojiti Svjetsko prvenstvo. Fangio je ostao poznat po tome što je dominirao Formulom 1 čitavo desetljeće i dandanas se smatra vicemajstorom Formule 1.</p>
        <p>Prvi Britanac koji je osvojio Svjetsko prvenstvo je bio Mike Hawthorn, donijevši Ferrariju naslov 1958. Međutim kada je Colin Chapman ušao u F1 kao dizajner šasija i kasnije osnivač Lotusovih automobila, Velika Britanija je dominirala Formulom 1 cijelo desetljeće. Pored Jima Clarka, Jackieja Stewarta, Jacka Brabhama, Grahama Hilla i Dennyja Hulmea, britanski timovi i njihovi vozači su osvojili 12 svjetskih prvenstava od 1962. do 1973. U sezoni 1962. uvedeno je novo vozilo s aluminijskom šasijom nazvanom monokok umjesto tradicionalne cjevaste šasije. 1968. Lotus je stavio reklamna slova Imperial Tobacca na vozilo i tako uveo sponzorstvo u taj sport. Aerodinamika je polako dobila važnost u dizajniranju vozila s pojavom aerofoila krajem 1960. Krajem sedamdesetih Lotus je uveo zemljani efekt aerodinamike koji je bolidima osigurao ogroman downforce i uvelike povećao brzinu na zavojima.</p>
        <p>Početkom devedesetih momčadi su uveli pomoćnog elektronskog vozača za upravljanje snagom motora, kontrolu protiv proklizavanja i poluautomatski mjenjač. Neke su posuđene od suvremenih cestovnih vozila. Aktivni ovjes je prvenstveno napravljen za stazu, a kasnije se probio na tržište osobnih automobila. FIA je zbog pritužbi da je tehnologija određivala rezultat utrka više nego vozačeva vještina zabranila 1994. mnogo takvih pomoćnih sredstava. Ipak mnogi promatrači su smatrali da je zabrana takvih pomoći vozačima zapravo bila zabrana zato što FIA nije imala neku tehnologiju koja bi eliminirala takve stvari u utrci. </p>
        <p>Na stazi momčad McLaren i Wiliams su dominirali 80-tima i 90-tim. Honda i McLaren su najviše dominirali u 80-tima dok je Renault pojačan Wiliamsovim vozačima dobio nekoliko Svjetskih prvenstava sredinom 90-tih, sve dok se Mclaren nije vratio krajem 90-tih.Rivalstvo između trkaćih legendi Senne i Prosta je postalo Formulina glavna zanimacija u sezoni 1988. i nastavila se sve dok se Prost nije povukao krajem 1993. Tragično i ironično, Senna je poginuo 1994. u zavoju Tamburelo na Velikoj nagradi San Marina i preuzeo je Prostovo vodstvo u Williamsu te godine. FIA je poboljšala sigurnosne standarde na stazi tako da od tog vikenda nijedan vozač nije poginuo za vrijeme utrke na stazi. </p>
        <div className="slikaLivo"><img src={Slika2}></img><br></br>Početak Velike Nagrade Australije 2003.</div>
        <br></br>
        <p>Vozači iz McLarena, Williamsa i Renaulta,te Ferrarija dobili su svako Svjetsko prvenstvo od 1984. do 2009. Zbog tehnoloških napredaka u 90-tima cijena natjecanja u Formuli 1 je dramatično porasla. To je povećalo financijski teret zajedno s dominacijom te velike četvorke koje su financirali veliki proizvođači automobila poput Daimler Chrysler, što je rezultiralo da male momčadi nisu financijski mogle opstati u Formuli 1. Financijski problemi su natjerali nekoliko timova da se povuku. Od 1990. 28 timova se povuklo iz Formule 1.</p>
        <p>Početkom 2000. dominirao je Michael Schumacher i uskrsli Ferrari. Početkom 21. st. oboreno je nekoliko Formulinih rekorda. 2001. Schumacher je postavio novi rekord u najvećem broju osvojenih Velikih nagrada, dok je raniji nositelj tog rekorda bio Alain Prost s 51 osvojenom Velikom nagradom. 2002. Schumacher je postavio još jedan novi rekord: najranije je osvojio Svjetsko prvenstvo vozača u sezoni osvojivši Veliku nagradu Francuske u srpnju te godine. 2003. Schumacher je osvojio 6. naslov svjetskog prvaka pobijedivši tako prijašnjeg nositelja rekorda Juan Manuel Fangia koji je osvojio 5 naslova. Schumacher i Ferrari nisu bili jedini rušitelji rekorda u tom razdoblju. 2003. Fernando Alonso postao je najmlađi osvajač prvog startnog mjesta u utrci kvalificirajući se na Velikoj nagradi Malezije 2003. Iste godine postao je najmlađi pobjednik Velike nagrade ikad pobijedivši na Velikoj nagradi Mađarske. Unatoč Ferrarijevoj dominaciji Kimi Räikkönen je imao teoretske šanse uzeti prvenstvo 2003. prije kraja sezone na Velikoj nagradi Japana. Juan Pablo Montoya je također bio blizu 2003. godine. Od 2005., od Velike nagrade Italije, Schumacher više nema teoretske šanse obraniti svoj naslov od Fernanda Alonsa i Kimi Räikkönena. </p>
        <p>Prvih nekoliko godina 21. st. u Formuli 1 bilo je nekoliko kontroverznih skandala. Na Velikoj nagradi Austrije Rubens Barrichello, Schumacherov momčadski kolega u Ferrariju koji je vodio utrku po naredbi iz boksa morao ga je propustiti. Nakon toga FIA je kaznila Ferrari i zabranila ostalim momčadima takvo miješanje u utrku. 2005. na Velikoj nagradi SAD izašlo je samo tri od 10 momčadi na stazu kada se ispostavilo da su Michelin gume preopasne za utrke.</p>
        <br></br>
        <div className="slikaDesno"><img src={Slika3}></img><br></br>Početak Velike Nagrade Kanade 2015.</div>
        <p>Velika promjena pravila u 2014. dovela je do zamjene 2,4-litrenih V8 motora s prirodnim usisavanjem 1,6-litrenim hibridnim pogonskim jedinicama s turbopunjačem. To je potaknulo Hondu da se vrati u sport 2015. kao četvrti proizvođač pogonskih jedinica u prvenstvu. Mercedes je postao dominantna sila nakon promjene pravila, s Lewisom Hamiltonom koji je osvojio prvenstvo, a odmah iza njega je bio njegov glavni rival i timski kolega, Nico Rosberg, s momčadi koja je te sezone pobijedila u 16 od 19 utrka. Momčad je nastavila u ovoj formi u sljedeće dvije sezone, ponovno pobijedivši u 16 utrka u 2015. prije nego što je odnijela rekordnih 19 pobjeda u 2016., pri čemu je Hamilton osvojio naslov u prvoj godini, a Rosberg ga je osvojio u potonjoj s pet bodova. U sezoni 2016. novi tim, Haas, pridružio se mreži, dok je Max Verstappen postao najmlađi pobjednik utrke u Španjolskoj s 18 godina.</p>
        <p>U 2022., upravno tijelo F1 najavilo je veliku promjenu pravila i dizajna automobila s namjerom promicanja bližih utrka korištenjem efekta tla, nove aerodinamike, većih kotača s niskoprofilnim gumama i redizajniranim propisima za nos i krilo. Red Bull se pojavio kao dominantna sila nakon promjene pravila. Konstruktorsko i vozačko prvenstvo 2022. i 2023. osvojili su Red Bull i Verstappen, s više utrka viška.</p>
        <p>Propisi koji reguliraju Formulu 1 trebali bi biti revidirani za sezonu 2026., s planiranim velikim promjenama kako bi se potaknule bliže i konkurentnije utrke. Promjene uključuju: potpuno održiva goriva, snaga MGU-K (Motor Generator Unit - Kinetic) povećana sa 120kW na 350kW, stroži sigurnosni zahtjevi</p>
      </div>
    );
  } 
export default Povijest;